In [8]:
import numpy as np

In [9]:
# Question 1
def add_matrices(A, B):
    return np.add(A, B)

def subtract_matrices(A, B):
    return np.subtract(A, B)

def multiply_matrices(A, B):
    return np.dot(A, B)

A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

print("\nAddition (A + B):\n", add_matrices(A, B))

print("\nSubtraction (A - B):\n", subtract_matrices(A, B))

print("\nMultiplication (A * B):\n", multiply_matrices(A, B))

print("\nMultiplication (B * A):\n", multiply_matrices(B, A))

Matrix A:
 [[1 2]
 [3 4]]

Matrix B:
 [[2 0]
 [1 2]]

Addition (A + B):
 [[3 2]
 [4 6]]

Subtraction (A - B):
 [[-1  2]
 [ 2  2]]

Multiplication (A * B):
 [[ 4  4]
 [10  8]]

Multiplication (B * A):
 [[ 2  4]
 [ 7 10]]


In [10]:
# Question 3
A = np.array([[2, 1],
              [3, -1]])

B = np.array([5, 4])

print("Coefficient Matrix A:\n", A)
print("\nConstant Matrix B:\n", B)

x = np.linalg.solve(A, B)
print("\nSolution vector x (decimal):")
print(f"x = {x[0]}")
print(f"y = {x[1]}")


Coefficient Matrix A:
 [[ 2  1]
 [ 3 -1]]

Constant Matrix B:
 [5 4]

Solution vector x (decimal):
x = 1.8
y = 1.4000000000000001


In [11]:
# Question 4
C = np.array([[1, 2, 3],
              [1, 1, 1],
              [3, 5, 7]])

print("Matrix C:\n", C)

# Calculate the determinant
det_C = np.linalg.det(C)
print(f"\nDeterminant of C: {det_C}")

# Calculate the rank of the matrix
rank_C = np.linalg.matrix_rank(C)
print(f"Rank of C: {rank_C}")

Matrix C:
 [[1 2 3]
 [1 1 1]
 [3 5 7]]

Determinant of C: 0.0
Rank of C: 2


In [12]:
# Question 5
D = np.array([[2, 1, 0],
              [1, 1, 1],
              [0, 1, 1]])

print("Matrix D:\n", D)

# Calculate the inverse of the matrix
inv_D = np.linalg.inv(D)
print("\nInverse of Matrix A:\n", inv_D)

# Verify that A * inv(A) equals I
verification = np.dot(D, inv_D)
print("\nVerification (D * inv_D):\n", verification)


Matrix D:
 [[2 1 0]
 [1 1 1]
 [0 1 1]]

Inverse of Matrix A:
 [[ 0.  1. -1.]
 [ 1. -2.  2.]
 [-1.  2. -1.]]

Verification (D * inv_D):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
